### ISSUE TITLE
Properly crediting your repo

### ISSUE THREAD

**Issue by Rinnegatamante** [Ryuzaki-MrL/NotifyMii#1]
https://github.com/Ryuzaki-MrL/NotifyMii/blob/master/source/notification.cpp#L72-L120 -> https://github.com/Rinnegatamante/Purgification/blob/master/source/main.cpp#L220-L275

https://github.com/Ryuzaki-MrL/NotifyMii/blob/master/source/notification.cpp#L135-L136 -> https://github.com/Rinnegatamante/Purgification/blob/master/source/main.cpp#L210-L211

https://github.com/Rinnegatamante/Purgification/blob/master/source/main.cpp#L32-L36 -> https://github.com/Ryuzaki-MrL/NotifyMii/blob/master/source/utils.cpp#L12-L16

https://github.com/Ryuzaki-MrL/NotifyMii/blob/master/source/utils.cpp#L6-L10 -> https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/include/utils.cpp#L76-L80

I think it's worth a mention :P

**Comment by Ryuzaki-MrL** [comment]
Oh, my bad :P 
As you can see on older commits, you were on the credits as most of the code was from Purgification. Then I rewrote my program, and forgot there was still some of your code on it.
This is fixed now!
